security:
  oauth2:
    # 是否使用DefaultTokenServices，用于测试客户端验证jwt
    default-token-services: false
    # 令牌存储类型: IN_MEMORY, JDBC, JWT, REDIS
    tokenStoreType: REDIS
    # Jwt密钥配置
#    jwt-key:
#      # 客户端密钥配置
#      client:
#        # 是否对称加密, 默认为true
#        symmetric: false
#        # 对称加密签名密钥
#        signing-key: cmmplb
#        # 非对称加密公钥文件路径
#        public-key-file-path: key/public.txt