##安全配置##
security:
  oauth2:
    client:
      client-id: spring_cloud_oauth2
      client-secret: 123456
      user-authorization-uri: http://@project.address@:@project.port@/server/oauth/authorize
      registered-redirect-uri: http://@project.address@:@project.port@/api/spring-boot-security-oauth2-auth
      access-token-uri: http://@project.address@:@project.port@/server/oauth/token
    resource:
      id: resource-server
      # user-info-uri和token-info-uri二选择即可
      # 如果配置了user-info-uri，该资源服务器使用userInfoTokenServices远程调用认证中心接口，
      # 通过认证中心的OAuth2AuthenticationProcessingFilter完成验证工作，一般设置user-info-uri即可
      user-info-uri: http://localhost:18083/user/info
      prefer-token-info: false
      # 该资源服务器使用RemoteTokenServices远程调用认证中心接口，注意一点就是如果使用token-info-uri那么就必须设置上clientId和clientSecret，
      # 通过CheckTokenEndpoint完成验证工作
      token-info-uri: http://localhost:@auth.port@/oauth/check_token
      #jwt:
      #  key-uri: http://@project.address@:@project.port@/server/oauth/token_key