security:
  # 是否开启资源拦截, 默认开启
  enabled: true
  # 配置白名单
  white-list:
    swagger: /**/doc.html/**/,/**/webjars/**,/**/swagger-ui.html**,/**/swagger-resources/**,/**/v2/api-docs/**,/**/v3/api-docs/**,/csrf
    js: /**/*.js
    css: /**/*.css
    favicon_ico: /**/favicon.ico
    application_info: /**/actuator/**,/**/instances/**
    system: /user/info/*,/user/info/mobile/*,/client/login
    # health: /health