# 调优参考：
#   https://blog.csdn.net/weixin_41922349/article/details/99655326
#   https://blog.csdn.net/wo18237095579/article/details/83276352
#   https://www.cnblogs.com/shihaiming/p/11590748.html
eureka:
  server:
    # 自我保护机制
    #   作用：
    #       网络短暂不稳定(网络偶尔抖动、短暂不可用)时保护 "服务的实例列表"，
    #       即禁止定时任务剔除失效的实例, 以免因为误判而清空部分服务的实例列表
    #   进入条件：
    #       最近1分钟接收到的全部服务的续约(通过client心跳机制维持租约)的次数小于指定阈值
    # ----------------------------------------------------------------------
    # 是否开启自我保护机制(true开启，false关闭) #客户端关闭、页面红色文字提示
    enable-self-preservation: false

  instance:
    # 执行当前服务的应用id，标识的是每一个具体的的服务(不可以重复)
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}@${server.port}
    # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    # 加上这个解决警告：c.n.eureka.cluster.PeerEurekaNodes: The replica size seems to be empty. Check the route 53 DNS Registry
    prefer-ip-address: true
    # 每隔5s发送一次心跳
    #lease-renewal-interval-in-seconds: 5
    # 告知服务端未xx秒内收到心跳，就将该服务移除列表，即xx秒未续约的服务实例, 参考server的缓存机制
    #lease-expiration-duration-in-seconds: 15
    # 状态页面路径
    status-page-url-path: /actuator/info
    # 健康检查路径
    health-check-url-path: /actuator/health

  client:
    enabled: true
    # 开启健康检查
    healthcheck.enabled: true
    # eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds: 30
    # 是否需要将自己注册给自己的注册中心（集群的时候是需要是为true）
    register-with-eureka: false
    # 是否检索注册中心的服务（单实例请设置为false，集群需要设置成true）
    fetch-registry: false
    # 将实例信息变更同步到 Eureka Server的初始延迟时间 ，默认为40秒
    initial-instance-info-replication-interval-seconds: 40
    # 连接eureka server的超时时间，默认为5秒
    eureka-server-connect-timeout-seconds: 10
    # 读取eureka server的超时时间，默认为8秒
    eureka-server-read-timeout-seconds: 15
    service-url:
      # 单机指向本身
      defaultZone: http://localhost:${server.port}/eureka

  dashboard:
    path: / #设置访问根路径